-- KOK Supabase Schema

-- Articles (generated by AI pipeline)
CREATE TABLE articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_title_en TEXT NOT NULL,
  issue_title_es TEXT NOT NULL,
  what_happened_en TEXT NOT NULL,
  what_happened_es TEXT NOT NULL,
  why_it_matters_en TEXT NOT NULL,
  why_it_matters_es TEXT NOT NULL,
  korean_reaction_summary_en TEXT NOT NULL,
  korean_reaction_summary_es TEXT NOT NULL,
  context_for_fans_en TEXT NOT NULL,
  context_for_fans_es TEXT NOT NULL,
  image_url TEXT DEFAULT '',
  issue_tags TEXT[] DEFAULT '{}',
  artist_tags TEXT[] DEFAULT '{}',
  sentiment TEXT DEFAULT 'neutral',
  reaction_sample_size INT DEFAULT 0,
  view_count INT DEFAULT 0,
  safety_level TEXT DEFAULT 'safe',
  source_url_hash TEXT UNIQUE,
  published_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_articles_published ON articles(published_at DESC);
CREATE INDEX idx_articles_tags ON articles USING GIN(issue_tags);
CREATE INDEX idx_articles_artists ON articles USING GIN(artist_tags);

-- Top reactions (Korean comments translated)
CREATE TABLE top_reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
  content_en TEXT NOT NULL,
  content_es TEXT NOT NULL,
  likes INT DEFAULT 0,
  source TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_reactions_article ON top_reactions(article_id);

-- Original source links
CREATE TABLE source_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT DEFAULT 'article'
);

CREATE INDEX idx_sources_article ON source_links(article_id);

-- User profiles
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname TEXT DEFAULT '',
  nationality TEXT DEFAULT '',
  favorite_tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User comments on articles
CREATE TABLE user_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  content TEXT NOT NULL,
  likes INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_comments_article ON user_comments(article_id);
CREATE INDEX idx_comments_user ON user_comments(user_id);

-- Processed URL hashes (to prevent reprocessing)
CREATE TABLE processed_urls (
  url_hash TEXT PRIMARY KEY,
  original_url TEXT NOT NULL,
  processed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Content pipeline run log
CREATE TABLE pipeline_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  candidates_found INT DEFAULT 0,
  articles_generated INT DEFAULT 0,
  articles_blocked INT DEFAULT 0,
  groq_calls INT DEFAULT 0,
  gemini_calls INT DEFAULT 0,
  status TEXT DEFAULT 'running'
);

-- RPC: increment comment likes
CREATE OR REPLACE FUNCTION increment_comment_likes(comment_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE user_comments SET likes = likes + 1 WHERE id = comment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: increment article view count
CREATE OR REPLACE FUNCTION increment_view_count(article_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE articles SET view_count = view_count + 1 WHERE id = article_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Row Level Security
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE top_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_comments ENABLE ROW LEVEL SECURITY;

-- Articles: public read
CREATE POLICY "Articles are viewable by everyone" ON articles FOR SELECT USING (true);

-- Reactions: public read
CREATE POLICY "Reactions are viewable by everyone" ON top_reactions FOR SELECT USING (true);

-- Source links: public read
CREATE POLICY "Sources are viewable by everyone" ON source_links FOR SELECT USING (true);

-- Profiles: users can read/update their own
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Comments: public read, authenticated write
CREATE POLICY "Comments are viewable by everyone" ON user_comments FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert comments" ON user_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own comments" ON user_comments FOR UPDATE USING (auth.uid() = user_id);
