import '../../models/news_article.dart';

class MockData {
  static List<NewsArticle> get sampleArticles => [
    NewsArticle(
      id: '1',
      issueTitleEn: 'NewJeans vs HYBE Lawsuit Escalates — Korean Internet Explodes',
      issueTitleEs: 'La demanda NewJeans vs HYBE se intensifica — Internet coreano explota',
      whatHappenedEn: 'NewJeans has officially filed a lawsuit against HYBE over contractual disputes and allegations of unfair treatment. The group claims they were sidelined after the Min Hee-jin controversy, with reduced promotions and resources.',
      whatHappenedEs: 'NewJeans ha presentado oficialmente una demanda contra HYBE por disputas contractuales y alegaciones de trato injusto. El grupo afirma que fueron marginadas después de la controversia de Min Hee-jin, con promociones y recursos reducidos.',
      whyItMattersEn: 'This is the biggest agency-vs-artist battle since the EXO-SM lawsuit era. It challenges HYBE\'s multi-label system and could reshape how K-pop contracts work. Korean GP sees this as a test of whether idols can fight back against major labels.',
      whyItMattersEs: 'Esta es la mayor batalla agencia-vs-artista desde la era de la demanda EXO-SM. Desafía el sistema multi-sello de HYBE y podría cambiar cómo funcionan los contratos de K-pop.',
      koreanReactionSummaryEn: '45% support NewJeans citing unfair treatment. 35% criticize the timing and methods. 20% neutral. Top sentiment: "They should have resolved this privately." Korean GP is fatigued by the ongoing saga but deeply invested.',
      koreanReactionSummaryEs: '45% apoya a NewJeans citando trato injusto. 35% critica el momento y los métodos. 20% neutral. Sentimiento principal: "Deberían haber resuelto esto en privado."',
      topReactions: [
        TranslatedReaction(id: 'r1', contentEn: '"I feel bad for the members. They\'re so young and already dealing with this mess. HYBE needs to take responsibility."', contentEs: '"Me siento mal por las miembros. Son tan jóvenes y ya están lidiando con esto. HYBE necesita asumir responsabilidad."', likes: 24521, source: 'Naver'),
        TranslatedReaction(id: 'r2', contentEn: '"As a Korean, I just want to see them perform again. The legal drama is exhausting for everyone."', contentEs: '"Como coreana, solo quiero verlas actuar de nuevo. El drama legal es agotador para todos."', likes: 15672, source: 'YouTube'),
        TranslatedReaction(id: 'r3', contentEn: '"Both sides have a point, but dragging this out in public hurts only the members. Settle it quietly."', contentEs: '"Ambos lados tienen razón, pero alargar esto en público solo daña a las miembros. Resuélvanlo en silencio."', likes: 18903, source: 'Naver'),
      ],
      contextForFansEn: 'In Korea, idol-agency lawsuits are extremely rare and seen as career-ending moves. The fact that NewJeans is pursuing this shows how serious the situation is. Korean law heavily favors agencies in entertainment contracts, making this an uphill battle.',
      contextForFansEs: 'En Corea, las demandas ídolo-agencia son extremadamente raras y se ven como movimientos que terminan carreras. El hecho de que NewJeans esté haciendo esto muestra lo seria que es la situación.',
      originalSources: [
        SourceLink(title: 'Naver News - Original Report', url: 'https://n.news.naver.com/article/example1', type: 'article'),
        SourceLink(title: 'HYBE Official Statement', url: 'https://hybecorp.com/statement', type: 'official'),
      ],
      imageUrl: 'https://picsum.photos/seed/nj_lawsuit/800/400',
      issueTags: ['CONTROVERSY', 'LEGAL', 'CONTRACT'],
      artistTags: ['NewJeans', 'HYBE', 'ADOR'],
      publishedAt: DateTime.now().subtract(const Duration(hours: 2)),
      sentiment: 'mixed',
      reactionSampleSize: 12840,
    ),
    NewsArticle(
      id: '2',
      issueTitleEn: 'aespa Makes History: First K-pop Group to Sell Out Tokyo Dome 3 Nights',
      issueTitleEs: 'aespa hace historia: Primer grupo de K-pop en agotar 3 noches en Tokyo Dome',
      whatHappenedEn: 'SM Entertainment\'s aespa sold out three consecutive nights at Tokyo Dome — 165,000+ fans total. The ticketing system crashed multiple times. This is the first time any K-pop group has achieved this milestone.',
      whatHappenedEs: 'aespa de SM Entertainment agotó tres noches consecutivas en el Tokyo Dome — más de 165,000 fans en total. El sistema de venta de boletos colapsó varias veces.',
      whyItMattersEn: 'Tokyo Dome is the ultimate benchmark for K-pop success in Japan. Even legendary groups like TVXQ and BIGBANG only did 1-2 nights. This cements aespa as the top 4th gen act in Japan and validates SM\'s strategy.',
      whyItMattersEs: 'El Tokyo Dome es el punto de referencia definitivo para el éxito del K-pop en Japón. Incluso grupos legendarios como TVXQ y BIGBANG solo hicieron 1-2 noches.',
      koreanReactionSummaryEn: '89% positive. Korean comments show genuine pride. Many compare this to legendary TVXQ concerts. Some debate whether this means aespa has surpassed other 4th gen groups.',
      koreanReactionSummaryEs: '89% positivo. Los comentarios coreanos muestran genuino orgullo. Muchos comparan esto con conciertos legendarios de TVXQ.',
      topReactions: [
        TranslatedReaction(id: 'r4', contentEn: '"Tokyo Dome 3 nights... the 4th gen is truly here. So proud of our girls! 🇰🇷"', contentEs: '"3 noches en el Tokyo Dome... la 4ta generación realmente ha llegado. ¡Muy orgulloso! 🇰🇷"', likes: 31205, source: 'Naver'),
        TranslatedReaction(id: 'r5', contentEn: '"SM finally managing a group properly lol. Congratulations aespa!"', contentEs: '"SM finalmente gestionando un grupo bien jaja. ¡Felicidades aespa!"', likes: 22100, source: 'YouTube'),
      ],
      contextForFansEn: 'Tokyo Dome (55,000 capacity) is considered the "holy grail" of concert venues in Asia. Selling it out is a major achievement; doing it 3 consecutive nights is unprecedented for K-pop. In Korean fan culture, Tokyo Dome concerts are used as a measuring stick for an artist\'s true popularity.',
      contextForFansEs: 'El Tokyo Dome (capacidad 55,000) es considerado el "santo grial" de los recintos de conciertos en Asia.',
      originalSources: [
        SourceLink(title: 'aespa Official YouTube', url: 'https://youtube.com/@aespa', type: 'official'),
        SourceLink(title: 'Naver News Report', url: 'https://n.news.naver.com/article/example2', type: 'article'),
      ],
      imageUrl: 'https://picsum.photos/seed/aespa_dome/800/400',
      issueTags: ['PERFORMANCE', 'CHART', 'WORLD_TOUR'],
      artistTags: ['aespa', 'SM'],
      publishedAt: DateTime.now().subtract(const Duration(hours: 5)),
      sentiment: 'positive',
      reactionSampleSize: 8420,
    ),
    NewsArticle(
      id: '3',
      issueTitleEn: 'BTS Jin Tops Billboard 200 — Korea Celebrates "The Wall"',
      issueTitleEs: 'Jin de BTS lidera el Billboard 200 — Corea celebra "El Muro"',
      whatHappenedEn: 'BTS member Jin\'s solo album debuted at #1 on Billboard 200, making him the highest-charting K-pop soloist in history. The album features pop ballads and upbeat tracks praised by Korean music critics.',
      whatHappenedEs: 'El álbum en solitario de Jin de BTS debutó en el #1 del Billboard 200, convirtiéndolo en el solista de K-pop con mejor posición en la historia.',
      whyItMattersEn: 'Jin achieved this right after completing military service — an incredible feat. Korean GP (general public, not just fans) is celebrating. The phrase "military service couldn\'t stop him" is trending on Korean portals. This proves BTS members can succeed individually.',
      whyItMattersEs: 'Jin logró esto justo después de completar el servicio militar — una hazaña increíble. El público general coreano está celebrando. La frase "el servicio militar no pudo detenerlo" es tendencia.',
      koreanReactionSummaryEn: '92% positive. Genuine pride from Korean GP, not just fans. "Military service couldn\'t stop him" is the top trending phrase. Even non-ARMY Koreans are impressed.',
      koreanReactionSummaryEs: '92% positivo. Orgullo genuino del público general coreano. "El servicio militar no pudo detenerlo" es la frase más trending.',
      topReactions: [
        TranslatedReaction(id: 'r6', contentEn: '"He came back from the military and went straight to Billboard #1. That\'s the definition of a wall. True legend."', contentEs: '"Regresó del servicio militar y fue directo al #1 de Billboard. La definición de un muro. Verdadera leyenda."', likes: 45200, source: 'Naver'),
        TranslatedReaction(id: 'r7', contentEn: '"I\'m not even an ARMY but I have to admit this is impressive. Korea\'s pride."', contentEs: '"Ni siquiera soy ARMY pero tengo que admitir que esto es impresionante. El orgullo de Corea."', likes: 38100, source: 'YouTube'),
      ],
      contextForFansEn: 'In Korea, "wall" (벽) means someone so dominant that no one can touch them. Military service (18 months) is mandatory for all Korean men and usually seen as a career pause. Jin proving otherwise has massive cultural significance.',
      contextForFansEs: 'En Corea, "muro" (벽) significa alguien tan dominante que nadie puede tocarlos. El servicio militar (18 meses) es obligatorio para todos los hombres coreanos.',
      originalSources: [
        SourceLink(title: 'Billboard Official', url: 'https://billboard.com/charts/billboard-200', type: 'article'),
        SourceLink(title: 'BIGHIT MUSIC Statement', url: 'https://bighit.com/news', type: 'official'),
      ],
      imageUrl: 'https://picsum.photos/seed/jin_bb200/800/400',
      issueTags: ['CHART', 'SOLO', 'MILITARY'],
      artistTags: ['BTS', 'HYBE'],
      publishedAt: DateTime.now().subtract(const Duration(hours: 8)),
      sentiment: 'positive',
      reactionSampleSize: 21500,
    ),
    NewsArticle(
      id: '4',
      issueTitleEn: 'LE SSERAFIM Coachella Encore Sparks Massive Vocal Debate in Korea',
      issueTitleEs: 'Encore de LE SSERAFIM en Coachella desata masivo debate vocal en Corea',
      whatHappenedEn: 'Fan-recorded videos of LE SSERAFIM\'s Coachella encore went viral on Korean social media. The unfiltered live vocals divided the Korean internet, reigniting debates about vocal training standards in modern K-pop.',
      whatHappenedEs: 'Videos de fans del encore de LE SSERAFIM en Coachella se viralizaron en redes sociales coreanas. Las voces en vivo sin filtro dividieron el internet coreano.',
      whyItMattersEn: 'This isn\'t just about one group — it\'s become a proxy war about whether K-pop has sacrificed vocal quality for choreography and visuals. Korean netizens are debating the entire training system. The controversy has led to comparisons with 2nd/3rd gen groups.',
      whyItMattersEs: 'Esto no es solo sobre un grupo — se ha convertido en una guerra indirecta sobre si el K-pop ha sacrificado la calidad vocal por la coreografía y los visuales.',
      koreanReactionSummaryEn: '68% critical, focusing on vocal ability. 22% defend the group citing nerves and extreme choreography at desert altitude. 10% neutral. This is one of the most-discussed topics on Korean portals this week.',
      koreanReactionSummaryEs: '68% crítico, enfocándose en la habilidad vocal. 22% defiende al grupo citando nervios y coreografía extrema a altitud desértica.',
      topReactions: [
        TranslatedReaction(id: 'r8', contentEn: '"This is embarrassing for K-pop as a whole. Companies need to invest more in vocal training, not just dance."', contentEs: '"Esto es vergonzoso para el K-pop en general. Las empresas necesitan invertir más en entrenamiento vocal."', likes: 52300, source: 'Naver'),
        TranslatedReaction(id: 'r9', contentEn: '"Why are people so harsh? They\'re performing intense choreography at altitude in the desert. Try singing while running."', contentEs: '"¿Por qué la gente es tan dura? Están bailando coreografía intensa en el desierto a gran altitud."', likes: 28700, source: 'YouTube'),
        TranslatedReaction(id: 'r10', contentEn: '"The real problem is HYBE pushing them to Coachella before they were ready. Blame the company, not the girls."', contentEs: '"El verdadero problema es HYBE empujándolas a Coachella antes de estar listas. Culpen a la empresa, no a las chicas."', likes: 19200, source: 'TheQoo'),
      ],
      contextForFansEn: 'Korean fans hold live vocals to extremely high standards. Unlike in the West where lip-syncing is more accepted, Korean audiences expect near-perfect live vocals even during intense choreography. Coachella\'s desert conditions (heat, altitude) make live singing much harder.',
      contextForFansEs: 'Los fans coreanos tienen estándares extremadamente altos para las voces en vivo. A diferencia de Occidente donde el lip-sync es más aceptado, las audiencias coreanas esperan voces perfectas.',
      originalSources: [
        SourceLink(title: 'Coachella Official', url: 'https://coachella.com', type: 'official'),
        SourceLink(title: 'Fan Recording - YouTube', url: 'https://youtube.com/watch?v=example', type: 'video'),
      ],
      imageUrl: 'https://picsum.photos/seed/lsf_coachella/800/400',
      issueTags: ['CONTROVERSY', 'PERFORMANCE'],
      artistTags: ['LE SSERAFIM', 'HYBE', 'SOURCE_MUSIC'],
      publishedAt: DateTime.now().subtract(const Duration(hours: 12)),
      sentiment: 'negative',
      reactionSampleSize: 34200,
    ),
    NewsArticle(
      id: '5',
      issueTitleEn: 'SEVENTEEN\'s \$200M World Tour Breaks All K-pop Records',
      issueTitleEs: 'La gira de \$200M de SEVENTEEN rompe todos los récords del K-pop',
      whatHappenedEn: 'SEVENTEEN\'s "Follow Again" world tour has grossed over \$200M across 50 cities — the highest-grossing K-pop tour in history. Most venues sold out within minutes of tickets going on sale.',
      whatHappenedEs: 'La gira "Follow Again" de SEVENTEEN ha recaudado más de \$200M en 50 ciudades — la gira de K-pop más taquillera de la historia.',
      whyItMattersEn: 'SEVENTEEN proved self-producing idols can achieve massive commercial success. Korean media is calling them "the complete package" — they write, choreograph, and produce their own content. This challenges the factory-idol narrative.',
      whyItMattersEs: 'SEVENTEEN demostró que los ídolos auto-productores pueden lograr éxito comercial masivo. Los medios coreanos los llaman "el paquete completo".',
      koreanReactionSummaryEn: '85% positive. Korean fans are proud but some express concern about the demanding schedule and members\' health. "Let them rest" is a common sentiment alongside the celebrations.',
      koreanReactionSummaryEs: '85% positivo. Los fans coreanos están orgullosos pero algunos expresan preocupación por la exigente agenda y la salud de los miembros.',
      topReactions: [
        TranslatedReaction(id: 'r11', contentEn: '"\$200M... SEVENTEEN is not a group, they\'re an economy at this point. Self-producing kings!"', contentEs: '"\$200M... SEVENTEEN no es un grupo, son una economía. ¡Reyes auto-productores!"', likes: 19800, source: 'Naver'),
        TranslatedReaction(id: 'r12', contentEn: '"Proud but worried. 50 cities is insane. Please let them rest properly between legs."', contentEs: '"Orgullosa pero preocupada. 50 ciudades es una locura. Por favor déjenlos descansar."', likes: 14500, source: 'YouTube'),
      ],
      contextForFansEn: 'SEVENTEEN is known as a "self-producing" group where members are heavily involved in songwriting and choreography. In Korea, this earns them extra respect compared to groups that rely entirely on external producers. The \$200M figure puts them alongside Western arena acts.',
      contextForFansEs: 'SEVENTEEN es conocido como un grupo "auto-productor" donde los miembros participan activamente en composición y coreografía.',
      originalSources: [
        SourceLink(title: 'Billboard Boxscore', url: 'https://billboard.com/boxscore', type: 'article'),
        SourceLink(title: 'PLEDIS Official', url: 'https://pledis.co.kr', type: 'official'),
      ],
      imageUrl: 'https://picsum.photos/seed/svt_tour/800/400',
      issueTags: ['WORLD_TOUR', 'CHART'],
      artistTags: ['SEVENTEEN', 'HYBE', 'PLEDIS'],
      publishedAt: DateTime.now().subtract(const Duration(hours: 18)),
      sentiment: 'positive',
      reactionSampleSize: 6700,
    ),
  ];
}
